---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-redis-slave
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dev/redis-slave
    repoURL: https://github.com/Myafq/gitops-example-devqa.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}